### ISSUE TITLE
Infrastructure and Configuration Management

### ISSUE THREAD

**Issue by vsth** [mjudeikis/openshift-mindmap#1]
Hi Mangidaz,

Very nice map!

I miss the infrastructure provider RHOSP, VMware and Baremetal and maybe also public providers GCP, AWS and Azure. Also Puppet as Configuration Management. Of course, ocp should be deployed with the buildin automation ansible. But if there are chef then puppet are maybe the better choice.

regards,
Thomas

**Comment by mjudeikis** [comment]
Thanks! Will update later today :)
