### ISSUE TITLE
Unable to access diagram in Lucid Chart

### ISSUE THREAD

**Issue by ghost** [mjudeikis/openshift-mindmap#3]
This is a great diagram. I clicked on the link (https://www.lucidchart.com/invitations/accept/70f2025f-83ff-4157-88e6-c10e45a40dbb)  and received access to a MindMaps folder but did not see this diagram there.  Thanks!

**Comment by gforster** [comment]
Any chance this can be addressed? It is exactly as described above

**Comment by mjudeikis** [comment]
moved. Lucid is no more :/
